/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotransversal.vistas;

/**
 *
 * @author marce
 */
public class ProyectoTransversalView extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoTransversalView
     */
    public ProyectoTransversalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMformuAlumno = new javax.swing.JMenu();
        jMalumno = new javax.swing.JMenuItem();
        jMformuMateria = new javax.swing.JMenu();
        jMmateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMformuInscripciones = new javax.swing.JMenuItem();
        jMcargaNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jMformuAlumno.setText("Alumno");

        jMalumno.setText("Formulario de Alumno");
        jMalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMalumnoActionPerformed(evt);
            }
        });
        jMformuAlumno.add(jMalumno);

        jMenuBar1.add(jMformuAlumno);

        jMformuMateria.setText("Materia");
        jMformuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMformuMateriaActionPerformed(evt);
            }
        });

        jMmateria.setText("Formulario de Materia");
        jMmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmateriaActionPerformed(evt);
            }
        });
        jMformuMateria.add(jMmateria);

        jMenuBar1.add(jMformuMateria);

        jMenu3.setText("Administracion");

        jMformuInscripciones.setText("Inscripcciones");
        jMformuInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMformuInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMformuInscripciones);

        jMcargaNotas.setText("Edicion de notas");
        jMcargaNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcargaNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jMcargaNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMenuItem5.setText("Alumnos por Materia");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMalumnoActionPerformed
        // activa ventana Gestion de alumnos
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeAlumnosView gda=new GestionDeAlumnosView();
        gda.setVisible(true);
        escritorio.add(gda);
        escritorio.moveToFront(gda);
    }//GEN-LAST:event_jMalumnoActionPerformed

    private void jMformuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMformuMateriaActionPerformed
        // activa la ventana Gestion de materias
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeMateriasView gdm=new GestionDeMateriasView();
        gdm.setVisible(true);
        escritorio.add(gdm);
        escritorio.moveToFront(gdm);
    }//GEN-LAST:event_jMformuMateriaActionPerformed

    private void jMformuInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMformuInscripcionesActionPerformed
        // activa ventana formulario inscripcciones
        escritorio.removeAll();
        escritorio.repaint();
        formuDeInscripcionView gdi=new formuDeInscripcionView();
        gdi.setVisible(true);
        escritorio.add(gdi);
        escritorio.moveToFront(gdi);
    }//GEN-LAST:event_jMformuInscripcionesActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // Indica la accion de cerrar ventana al seleccionar boton jMSalir
        dispose();
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmateriaActionPerformed
        // activa ventana Gestion de materias
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeMateriasView gdm=new GestionDeMateriasView();
        gdm.setVisible(true);
        escritorio.add(gdm);
        escritorio.moveToFront(gdm);
    }//GEN-LAST:event_jMmateriaActionPerformed

    private void jMcargaNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcargaNotasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CargaDeNotasView cdn=new CargaDeNotasView();
        cdn.setVisible(true);
        escritorio.add(cdn);
        escritorio.moveToFront(cdn);
    }//GEN-LAST:event_jMcargaNotasActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        alumnosXmateriaView axm=new alumnosXmateriaView();
        axm.setVisible(true);
        escritorio.add(axm);
        escritorio.moveToFront(axm);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoTransversalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoTransversalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuItem jMalumno;
    private javax.swing.JMenuItem jMcargaNotas;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu jMformuAlumno;
    private javax.swing.JMenuItem jMformuInscripciones;
    private javax.swing.JMenu jMformuMateria;
    private javax.swing.JMenuItem jMmateria;
    // End of variables declaration//GEN-END:variables
}
